-- Reconstruido desde el schema de Polars del ETL.
-- Verificar contra producción: SHOW CREATE TABLE sinpagt
-- Pendiente: sinpagt_agg se referencia en la query de control pero su DDL no está versionado.
CREATE TABLE IF NOT EXISTS sinpagt (
    CodRama UInt32,
    Siniestro UInt32,
    NroLiquidacion UInt32,
    CodItemPago String,
    FechaPago Date,
    CodCausa UInt32,
    NroAsegurado UInt32,
    CodOrganizador UInt32,
    CodProductor UInt32,
    TipoMovimiento String,
    TipoLiquidacion String,
    Clasereserva UInt32,
    TipoAcreedor String,
    CodAcreedor UInt32,
    CodMayorAuxiliar String,
    NroMayorAuxiliar UInt32,
    Pagado String,
    Proceso String,
    EstadoIngreso String,
    CantFrentes UInt32,
    Op UInt32,
    NroBeneficiario UInt32,
    TipoReserva String,
    CodRiesgo String,
    CoberturaReservada UInt32,
    ItemPago String,
    FechaDenuncia Date,
    FechaOcurrencia Date,
    DireccionSiniestro String,
    CpSiniestro UInt32,
    MarcaFueraTermino String,
    CodTerminado String,
    CodUbicacion String,
    FueraVigencia String,
    PolizaAnulada String,
    EnCaducidad String,
    ComponenteBaja String,
    Conductor UInt32,
    CondHabitual String,
    Poliza UInt32,
    Supl UInt32,
    Comp UInt32,
    CodCoberturaAut String,
    SumaAseguradaAut UInt32,
    CodInderProvinciaAut UInt32,
    CodMarcaAu String,
    CodModeloAu String,
    AnioVehiculoAut UInt32,
    OrigenVehiculoAut String,
    CodTipoVehiculoAut UInt32,
    CodUsoVehiculoAut UInt32,
    Importe Float32
)
ENGINE = MergeTree
PARTITION BY toYYYYMM(FechaPago)
ORDER BY (CodRama, Siniestro, NroLiquidacion, CodItemPago);
