CREATE TABLE sehpm151t (
    `Op` UInt32,
    `Suplemento` UInt32,
    `CodTipoOp` UInt32,
    `CodSubTipoOp` UInt32,
    `PlVidaNvaRen` UInt32,
    `CodRama` UInt32,
    `Poliza` UInt32,
    `NroAsegurado` UInt32,
    `CpAsegurado` UInt32,
    `CpSufijoAsegurado` UInt32,
    `NombreAsegurado` String,
    `LocalidadAsegurado` String,
    `ProvinciaAsegurado` String,
    `CodOrganizador` UInt32,
    `CodProductor` UInt32,
    `SumaAsegurada` Float64 DEFAULT 0.0,
    `PrimaNeta` Float64 DEFAULT 0.0,
    `RecFin` Float64 DEFAULT 0.0,
    `RecAdm` Float64 DEFAULT 0.0,
    `DerEmision` Float64 DEFAULT 0.0,
    `SellRiesgo` Float64 DEFAULT 0.0,
    `ImpInt` Float64 DEFAULT 0.0,
    `ServSoc` Float64 DEFAULT 0.0,
    `TasaSsn` Float64 DEFAULT 0.0,
    `Iva` Float64 DEFAULT 0.0,
    `IvaPercepcion` Float64 DEFAULT 0.0,
    `IvaRespNoInscr` Float64 DEFAULT 0.0,
    `BonifPrima` Float64 DEFAULT 0.0,
    `Acc` Float64 DEFAULT 0.0,
    `RecCapital` Float64 DEFAULT 0.0,
    `FEmision` Date,
    `FVigDesde` Date,
    `FVigHasta` Nullable(Date),
    `PrimaTarifa` Float64 DEFAULT 0.0,
    `PremioBruto` Float64 DEFAULT 0.0,
    `CodOrganizadorComision` UInt32,
    `ComOrganizador` Float64  DEFAULT 0.0,
    `CodProductorComision` UInt32,
    `ComProductor` Float64  DEFAULT 0.0
) ENGINE = MergeTree PARTITION BY toYYYYMM(FEmision)
ORDER BY
    (
    	toYYYYMM(FEmision),
        CodOrganizador,
        CodProductor,
        NroAsegurado,
        CpAsegurado,
        CpSufijoAsegurado,
        Op,
        Suplemento
    ) SETTINGS index_granularity = 8192;


CREATE TABLE reportes.sehpm151t_agg (
    `FEmisionMes` Date,
    `CodRama` UInt32,
    `CodOrganizador` UInt32,
    `CodProductor` UInt32,
    `CodTipoOp` UInt32,
    `CodSubTipoOp` UInt32,
    `Poliza` UInt32,
    `NroAsegurado` UInt32,
    `SumaAseguradaMillones` Int32,
    `PrimaNeta` Float64,
    `RecFin` Float64,
    `RecAdm` Float64,
    `DerEmision` Float64,
    `SellRiesgo` Float64,
    `ImpInt` Float64,
    `ServSoc` Float64,
    `TasaSsn` Float64,
    `Iva` Float64,
    `IvaPercepcion` Float64,
    `IvaRespNoInscr` Float64,
    `BonifPrima` Float64,
    `Acc` Float64,
    `RecCapital` Float64,
    `PrimaTarifa` Float64,
    `PremioBruto` Float64,
    `ComOrganizador` Float64,
    `ComProductor` Float64,
    `Cantidad` Int32
) ENGINE = SummingMergeTree PARTITION BY toYYYYMM(FEmisionMes)
ORDER BY
    (
        FEmisionMes,
        CodRama,
        CodOrganizador,
        CodProductor,
        CodTipoOp,
        CodSubTipoOp,
        Poliza,
        NroAsegurado,
        SumaAseguradaMillones
    ) SETTINGS index_granularity = 8192;


CREATE MATERIALIZED VIEW reportes.sehpm151t_agg_mv TO reportes.sehpm151t_agg (
    `FEmisionMes` Date,
    `CodRama` UInt32,
    `CodOrganizador` UInt32,
    `CodProductor` UInt32,
    `CodTipoOp` UInt32,
    `CodSubTipoOp` UInt32,
    `Poliza` UInt32,
    `NroAsegurado` UInt32,
    `SumaAseguradaMillones` Int32,
    `PrimaNeta` Float64,
    `RecFin` Float64,
    `RecAdm` Float64,
    `DerEmision` Float64,
    `SellRiesgo` Float64,
    `ImpInt` Float64,
    `ServSoc` Float64,
    `TasaSsn` Float64,
    `Iva` Float64,
    `IvaPercepcion` Float64,
    `IvaRespNoInscr` Float64,
    `BonifPrima` Float64,
    `Acc` Float64,
    `RecCapital` Float64,
    `PrimaTarifa` Float64,
    `PremioBruto` Float64,
    `ComOrganizador` Float64,
    `ComProductor` Float64,
    `Cantidad` Int32
) AS
SELECT
	toStartOfMonth(FEmision) AS FEmisionMes,
	CodRama,
	CodOrganizador,
	CodProductor,
	CodTipoOp,
	CodSubTipoOp,
	Poliza,
	NroAsegurado,
	toInt32(sum(SumaAsegurada) / 1000000) AS SumaAseguradaMillones,
	sum(PrimaNeta) AS PrimaNeta,
	sum(RecFin) AS RecFin,
	sum(RecAdm) AS RecAdm,
	sum(DerEmision) AS DerEmision,
	sum(SellRiesgo) AS SellRiesgo,
	sum(ImpInt) AS ImpInt,
	sum(ServSoc) AS ServSoc,
	sum(TasaSsn) AS TasaSsn,
	sum(Iva) AS Iva,
	sum(IvaPercepcion) AS IvaPercepcion,
	sum(IvaRespNoInscr) AS IvaRespNoInscr,
	sum(BonifPrima) AS BonifPrima,
	sum(Acc) AS Acc,
	sum(RecCapital) AS RecCapital,
	sum(PrimaTarifa) AS PrimaTarifa,
	sum(PremioBruto) AS PremioBruto,
	sum(ComOrganizador) AS ComOrganizador,
	sum(ComProductor) AS ComProductor,
	toInt32(count()) AS Cantidad
FROM
	reportes.sehpm151t
GROUP BY
	FEmisionMes,
	CodRama,
	CodOrganizador,
	CodProductor,
	CodTipoOp,
	CodSubTipoOp,
	Poliza,
	NroAsegurado;


CREATE TABLE reportes.sehpm151t_perfiles_agg (
    `FEmisionMes` Date,
    `CodRama` UInt32,
    `CodOrganizador` UInt32,
    `CodProductor` UInt32,
    `NroAsegurado` UInt32,
    `SumaAseguradaMillones` Int32,
    `PrimaNeta` Float64,
    `RecFin` Float64,
    `RecAdm` Float64,
    `DerEmision` Float64,
    `SellRiesgo` Float64,
    `ImpInt` Float64,
    `ServSoc` Float64,
    `TasaSsn` Float64,
    `Iva` Float64,
    `IvaPercepcion` Float64,
    `IvaRespNoInscr` Float64,
    `BonifPrima` Float64,
    `Acc` Float64,
    `RecCapital` Float64,
    `PrimaTarifa` Float64,
    `PremioBruto` Float64,
    `ComOrganizador` Float64,
    `ComProductor` Float64,
    `Cantidad` Int32
) ENGINE = SummingMergeTree PARTITION BY toYYYYMM(FEmisionMes)
ORDER BY
    (
        FEmisionMes,
        CodRama,
        CodOrganizador,
        CodProductor,
        NroAsegurado,
        SumaAseguradaMillones
    ) SETTINGS index_granularity = 8192;


